<?php
$repos=array(
	array(
		"name"=>"Isengard",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/isengard/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/isengard",
		"md5URL"=>"http://mirrors.xbmc.org/addons/isengard/addons.xml.md5"),
	array(
		"name"=>"Helix",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/helix/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/helix",
		"md5URL"=>"http://mirrors.xbmc.org/addons/helix/addons.xml.md5"),
	array(
		"name"=>"Gotham",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/gotham/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/gotham",
		"md5URL"=>"http://mirrors.xbmc.org/addons/gotham/addons.xml.md5"),
	array(
		"name"=>"Frodo",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/frodo/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/frodo",
		"md5URL"=>"http://mirrors.xbmc.org/addons/frodo/addons.xml.md5"),
	array(
		"name"=>"Eden",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/eden/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/eden",
		"md5URL"=>"http://mirrors.xbmc.org/addons/eden/addons.xml.md5"),
	array(
		"name"=>"Dharma",
		"xmlURL"=>"http://mirrors.xbmc.org/addons/dharma/addons.xml",
		"repoURL"=>"http://mirrors.xbmc.org/addons/dharma",
		"md5URL"=>"http://mirrors.xbmc.org/addons/dharma/addons.xml.md5"));
?>
